### ISSUE TITLE
Can't Recognize Device

### ISSUE THREAD

**Issue by ocket8888** [vividnightmare/g510s#6] opened 2018-10-27 06:18 UTC
after starting the application (after first reloading udev rules), it is seemingly unable to recognize my g510s keyboard. unplugging the keyboard and plugging it back in had no effect, neither did re-starting the application after doing so.

**Comment by vividnightmare** [comment] 2018-10-27 06:23
Do you get any output when you run `lsusb | grep 046d:c22`?

**Comment by ocket8888** [comment] 2018-10-27 06:27
I just powered my computer down for the night - maybe that'll help for some reason - but I'll give that a whirl tomorrow

**Comment by ocket8888** [comment] 2018-10-27 14:45
Reboot didn't help, and yeah `lsusb` has my keyboard:
```
Bus 001 Device 002: ID 046d:c22d Logitech, Inc. G510 Gaming Keyboard
```

**Comment by vividnightmare** [comment] 2018-10-27 15:59
It should find the device then.  I would suspect you don't have permissions to read it.

Run the program with `g510s --debug 1` to enable debugging in libg15 and you should get more descriptive output in the terminal.

**Comment by ocket8888** [comment] 2018-10-27 16:35
yeah, that appears to be the case: 
```
libusb: error [_get_usbfs_fd] libusb couldn't open USB device /dev/bus/usb/001/002: Permission denied
libusb: error [_get_usbfs_fd] libusb requires write access to USB device nodes.
```

**Comment by vividnightmare** [comment] 2018-10-27 16:37
You would need to check that your udev rules are working properly.

You need to be a member of the group `plugdev` to have access per the provided rules.  If you're already a member try updating the udev rules with `udevadm control --reload` and `udevadm trigger`

**Comment by ocket8888** [comment] 2018-10-27 16:40
the `plugdev` group doesn't exist on my system...

**Comment by vividnightmare** [comment] 2018-10-27 16:42
You'll need to create it and add your user to it and then the rules should work, given that they're loaded.

**Comment by ocket8888** [comment] 2018-10-27 16:48
created the group, added myself to it, logged out and logged back in, reloaded the udev rules with `sudo udevadm control --reload && sudo udevadm trigger` and the problem persists - `libusb requires write access to USB device nodes`

**Comment by vividnightmare** [comment] 2018-10-27 17:23
I really don't know.  It's probably something Arch doesn't like about the rule, its syntax, or something else...

You can run g510s as root to see if you get access and, if it does, would indicate that the issue is with the udev rule.

**Comment by vividnightmare** [comment] 2018-10-27 18:04
It could be the rules aren't in the correct directory.  The installation places it at `/lib/udev/rules.d` but Arch's wiki indicates they want them in `/etc/udev/rules.d` or `/usr/lib/udev/rules.d`

**Comment by ocket8888** [comment] 2018-10-27 20:40
I tried moving the rules to both those locations without success - reloading rules in between each, of course.

Running as root allowed me to change the colors, but I don't see anything on the LCD like e.g. a clock. Debug output shows:
```
loadG15Font: NONE/share/g15tools/fonts/G15/default-02.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-02.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-01.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-01.fnt"

(g510s:6728): libappindicator-WARNING **: 14:36:07.270: Unable to get the session bus: Error spawning command line “dbus-launch --autolaunch=551ec4a3f36e446a96be28a96a5ad7b9 --binary-syntax --close-stderr”: Child process exited with code 1

(g510s:6728): LIBDBUSMENU-GLIB-WARNING **: 14:36:07.270: Unable to get session bus: Error spawning command line “dbus-launch --autolaunch=551ec4a3f36e446a96be28a96a5ad7b9 --binary-syntax --close-stderr”: Child process exited with code 1
loadG15Font: NONE/share/g15tools/fonts/G15/default-02.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-02.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-39.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-39.fnt"
loadG15Font: NONE/share/g15tools/fonts/G15/default-01.fnt doesn't exist or has permissions problem.
libg15render: Unable to load font "NONE/share/g15tools/fonts/G15/default-01.fnt"
```

**Comment by vividnightmare** [comment] 2018-10-27 20:47
So the device works and can be accessed by libg15.  You'll need to follow up with Arch people on their forums or IRC, for example, to find out why the udev rules aren't working.  I'm not familiar with Arch or their philosophy so I really can't tell you why they don't work.  They do work here in Debian-land.

When you find out why the udev rules aren't working, please post the solution here so it can be referenced in the future.  I would guess it has something to do with syntax or system configuration.

As for the latter, open a new issue.

**Comment by ocket8888** [comment] 2018-10-31 13:15
Finally worked up the courage to wade back into the Arch forums, related topic: https://bbs.archlinux.org/viewtopic.php?pid=1814604#p1814604

**Comment by vividnightmare** [comment] 2018-10-31 17:27
Ok.  Hopefully someone will have a better understanding of what Arch is expecting in this case.  You may also want to try `irc.freenode.net #archlinux` for a more interactive and, possibly, quicker discussion.

Your other issue should be easier to solve, but it would be best to discuss that in an issue of its own.  (The files are supplied by libg15render)

**Comment by ocket8888** [comment] 2018-10-31 17:44
For sure. Dealing with some issues related to switching DE from Gnome3 to Cinnamon atm, but when I'm back to a place where I can click on things I'll open a new issue - can't test anything the way things are right now.

**Comment by vividnightmare** [comment] 2019-04-25 21:26
Closing for now.  Re-open to continue or with new information.

**Closed as completed by vividnightmare** 2019-04-25 21:26 UTC
Labels: Arch Linux, udev
