### ISSUE TITLE
Any chance the configs could be stored in text files so they can configured with scripts?

### ISSUE THREAD

**Issue by Drek282** [vividnightmare/g510s#8] opened 2019-04-18 21:39 UTC
This would allow for an infinite number of easily configurable profiles.  The gui is fantastic, I love it, and I love the fact that I'm able to use my keyboard on Linux, but it would be nice to be able to use the full capabilities of bash scripting to allow for an infinite number of profiles, and profile loading using scripts, etc.

**Comment by vividnightmare** [comment] 2019-04-18 21:59
Currently, there is no config really.  The program simply dumps the data/arrays into a blob when you quit or save and tries to load such blob when it starts up.  The blob contains basically all the settings found in the GUI.

It could be done though.  There would need to be code that formats and writes the settings and parses and loads them.  This is done to some extent, but no conversion is made that makes the data human readable.  I didn't do this when I wrote it because it was not necessary to getting my keyboard working.

I'm also not in a position where I can spend time adding new features.  There are several items on the to do list here, but I just don't have the time to implement them with work and the other development groups I'm working in.

Patches would definitely be welcome though.

**Comment by Drek282** [comment] 2019-04-18 23:18
Is there any tool you might suggest to edit the blob in a coherent way without destroying it?  xxd? perl?  I have looked at the blob and I can see the text fields in it.

**Comment by Drek282** [comment] 2019-04-18 23:20
What I'm looking for is a fairly simple way to edit the blob using bash, so that I can load configs using a script, instead of having to reconfigure manually.  I use my keyboard for a lot of different applications and four profiles just doesn't cut it.

**Comment by vividnightmare** [comment] 2019-04-18 23:55
The easiest way to edit the blob would be to use the GUI.

That being said, you would need to modify the code to accept more data.  This information is loaded into memory and additional values that you add would almost certainly cause a fault.

Expanding the data structure would allow you to add as many different profiles as you like, but you would need to modify the GUI to display those and allow you to edit them.  This would probably be the most time consuming part of such a process.  You could edit it in another way, but I don't have any suggestions in that regard.  Reference https://github.com/vividnightmare/g510s/blob/689d70571a4605b886237b77e75ed43077df9b5b/g510s.h#L102

You would also need a way to swap to them, perhaps Shift+M1 or whatever you'd like.  And this should be relatively easy once the data structures are all set up.  Reference https://github.com/vividnightmare/g510s/blob/689d70571a4605b886237b77e75ed43077df9b5b/g510s-keys.c#L185

You could also work around the issue by using multiple blobs that you've saved.  For example, you could save two of them (you would have to rename them because the program only wants the one) and swap to the one you want via a script that copies and renames them so that the program gets the one you want.  You would need to restart the program to get it to load it though, or modify it such that you can call load_config() from the GUI or something.  Reference https://github.com/vividnightmare/g510s/blob/689d70571a4605b886237b77e75ed43077df9b5b/g510s.c#L225

**Comment by Drek282** [comment] 2019-04-19 00:25
All you would need would be to load a  text file into the current structure, in a similar fashion to the g13 software with a designation of which profile to load into.  Below is what they look like.  Even a relatively simple command line interface, such as that used by ratbagctl.

For people that only want to use a gui, they can be happy with the current four profiles, and reconfiguring them.  For people like me it would allow the use of scripts to configure the keys.  There must be a relatively simple way to allow for editing the data blob, without having to build an entirely new gui.

```
bind BD KEY_F1
bind L1 KEY_F2
bind L2 KEY_F3
bind L3 KEY_F4
bind L4 KEY_F5

bind M1 KEY_F6
bind M2 KEY_F7
bind M3 KEY_F8
bind MR KEY_F9

bind G1 KEY_ESC
bind G2 KEY_1
bind G3 KEY_2
bind G4 KEY_3
bind G5 KEY_6
bind G6 KEY_7
bind G7 KEY_R

bind G8 KEY_KPASTERISK
bind G9 KEY_4
bind G10 KEY_5
bind G11 KEY_6
bind G12 KEY_4
bind G13 KEY_F
bind G14 KEY_0

bind G15 KEY_LEFTSHIFT
bind G16 KEY_LEFTBRACE
bind G17 KEY_5
bind G18 KEY_B
bind G19 KEY_9

bind G20 KEY_SPACE
bind G21 KEY_RIGHTBRACE
bind G22 KEY_MINUS
```

**Comment by Drek282** [comment] 2019-04-19 00:38
Anyway, I want you to know I very much appreciate the time you did put into this, and I don't want you to put more time into this that you can't afford to spend.  I'm thinking about learning how to code, maybe I'll be able to do something with it myself at some point.

**Comment by Drek282** [comment] 2019-04-19 00:39
I do have a question though.  Is there any way to directly bind a key to the the G keys?  So far I've been doing it with xdotool, which works, but doesn't allow for a key that you press and hold.

**Comment by vividnightmare** [comment] 2019-04-19 18:17
It should be possible.  Have a look at how the keys are handled, specifically the multimedia keys which are mapped to actual keys and do the same thing for the G keys.
https://github.com/vividnightmare/g510s/blob/689d70571a4605b886237b77e75ed43077df9b5b/g510s-keys.c#L111
https://github.com/vividnightmare/g510s/blob/689d70571a4605b886237b77e75ed43077df9b5b/g510s-keys.c#L288

**Comment by Drek282** [comment] 2019-04-19 20:31
That's interesting, thank you.  First time I've looked at source code and it actually made sense... :)

**Comment by vividnightmare** [comment] 2019-04-25 21:30
Closing as technically not a bug.  Feel free to contact.  Patches always welcome.

**Closed as completed by vividnightmare** 2019-04-25 21:30 UTC
Labels: Suggestion, Config
